apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-auth
    namespace: kube-system
data:
    mapUsers: |
        - groups:
          - system:masters
          userarn: arn:aws:iam::237947248857:user/Github_CI
          username: github-ci
    mapRoles: |
        - groups:
          - system:bootstrappers
          - system:nodes
          rolearn: arn:aws:iam::237947248857:role/AWS_EKS_Node_Role
          username: system:node:{{EC2PrivateDNSName}}
