name: Deploy to production

on:
    push:
        branches: ["master"]
        paths: ["**.go"]
    workflow_dispatch:

jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  role-duration-seconds: 1200
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  role-skip-session-tagging: true

            - name: Sts GetCallerIdentity
              run: |
                  aws sts get-caller-identity

            # - name: Login to Amazon ECR
            #   id: login-ecr
            #   uses: aws-actions/amazon-ecr-login@v2

            # - name: Build, tag, and push docker image to Amazon ECR
            #   env:
            #       REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            #       REPOSITORY: simple-bank
            #       IMAGE_TAG: ${{ github.sha }}
            #   run: |
            #       docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            #       docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
