name: Deploy to production

on:
    push:
        branches: ["master"]
        paths: ["**.go"]
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "latest"
              id: install-kubectl

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: us-west-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Load secrets and save to app.env
              run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > src/app.env

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: simple-bank
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
                  docker push -a $REGISTRY/$REPOSITORY

            - name: Update Kube Config
              run: aws eks update-kubeconfig --name simple-bank --region us-west-1

            - name: Deploy image to Amazon EKS
              run: |
                  kubectl apply -f eks/aws-auth.yaml
                  kubectl apply -f eks/deployment.yaml
                  kubectl apply -f eks/service.yaml
                  kubectl apply -f eks/issuer.yaml
                  kubectl apply -f eks/ingress.yaml
                  kubectl rollout restart deploy simple-bank-api-deployment
